In [ ]:
#1 Create a 1D NumPy array containing the integers from 0 to 9.
import numpy as np
a=np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#2 Create a 2D NumPy array of shape (3, 3) with values ranging from 1 to 9.
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
#2
import numpy as np
a=np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#3 Create a 3x3 identity matrix using NumPy.
import numpy as np
a=np.zeros((3,3))
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
#3 Create a 3x3 identity matrix using NumPy.
import numpy as np
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#4 Generate a NumPy array of 10 random numbers between 0 and 1.
import numpy as np
a=np.arange(0.1,2,0.1)
print(a)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8
 1.9]


In [7]:
#4 Generate a NumPy array of 10 random numbers between 0 and 1.
import numpy as np
a=np.random.rand(10) #rand 0 to 1 print avollu
print(a)

[0.8105974  0.44679013 0.0405825  0.15570991 0.34780753 0.56622064
 0.5303708  0.14407419 0.5013929  0.76252266]


In [8]:
#4
import numpy as np
a=np.random.rand(2,2)
print(a)

[[0.4803519  0.11628285]
 [0.87235261 0.62916509]]


In [ ]:
# 5 Create an array of 10 zeros and another of 10 ones.
import numpy as np
arr=np.zeros(10)
brr=np.ones(10)
print(arr)
print(brr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#6 Given the array a = np.array([10, 20, 30, 40, 50]), access the third element.
import numpy as np
a=np.array([10,20,30,40,50])
print(a[2])

30


In [ ]:
#7 Create a 4x4 matrix and access the element at the second row, third column.
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a)
b=a[1,2]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
7


In [9]:
#8 Access the last element of the array a = np.array([5, 10, 15, 20, 25]).
import numpy as np
a=np.array([5,10,15,20,25])
print(a)
b=a[-1]
print(b)

[ 5 10 15 20 25]
25


In [ ]:
#9
a=np.array([1,3,5,7,9,11])
print(a)
b=(a[1],a[3],a[4])
print(b)

[ 1  3  5  7  9 11]
(3, 7, 9)


In [10]:
#9. For the array a = np.array([1, 3, 5, 7, 9, 11]), access the elements at indices 1, 3, and4
a=np.array([1,3,5,7,9,11])
b=a[[1,3,4]]
print(b)

[3 7 9]


In [14]:
#10 .Create a 3D array of shape (2, 2, 2) and access the element at position (1, 1, 1).
import numpy as np
a=np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]],[[12,13,14],[15,16,17]]])
b=a[1,1,1]
print(a)
print(b)

[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
10


In [15]:
#10 crct
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b=a[1,1,1]
print(b)

8


In [ ]:
#11.Given the array a = np.array([2, 4, 6, 8, 10, 12]), slice it to get the first 3 elements.
a=np.array([2,4,6,8,10,12])
b=a[0:3]
print(a)
print(b)

[ 2  4  6  8 10 12]
[2 4 6]


In [ ]:
#12.Create a 4x4 array and slice it to get the first two rows and last two columns.
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[:2,2:])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]


In [19]:
#12 crct
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a)
print(a[:2,-2:])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[3 4]
 [7 8]]


In [20]:
#13 .For the array a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), slice it to get every second
element.
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8,9])
print(a[::2])

[0 2 4 6 8]


In [21]:
#14.Slice the last two elements from each row of a 3x4 array.
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[:,-2:]
print(b)

[[ 3  4]
 [ 7  8]
 [11 12]]


In [22]:
# 15.Create a 5x5 matrix and slice out the inner 3x3 matrix.
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
b=a[1:4,1:4]
print(b)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [28]:
#16.Create an array of integers from 0 to 5 and change its data type to float.
import numpy as np
a=np.arange(6)
b=a.astype("f")
print(b.dtype)


float32


In [31]:
#17.Create a NumPy array of shape (3, 3) with boolean values (True/False).
import numpy as np
a=np.array([[True,False,True],[True,False,True],[True,False,True]])
print(a)

[[ True False  True]
 [ True False  True]
 [ True False  True]]


In [30]:
#18.Create an array of complex numbers (e.g., [1+2j, 3+4j, 5+6j]).
import numpy as np
a=np.array([1+2j,3+4j,5+6j])
print(a)

[1.+2.j 3.+4.j 5.+6.j]


In [33]:
# 19.Given an array of strings (e.g., ["1", "2", "3"]), convert it to an array of integers.
import numpy as np
a=np.array(["1","2","3"])
b=a.astype(int)
print(b)

[1 2 3]


In [34]:
# 20.Create an array of float values and then convert it to an integer type.
import numpy as np
a=np.array([1.1,1.2,2.1,2.2])
b=a.astype(int)
print(b)

[1 1 2 2]
